package com.pluralsight.java8.arrays.examples;

/**
 * Example 6: Arrays are objects.
 */
public class Example06 {

    public static void main(String[] args) {
        int[] numbers = {16, 23, 30, 41};
        String[] names = {"Susan", "John", "Betty", "Mark"};

        // For each type of array, there is a special class, generated by the compiler.
        // (You don't need to understand the internal names of the array classes for the certification exam).
        System.out.println("The class of the array of int is: " + numbers.getClass().getName());
        System.out.println("The class of the array of String is: " + names.getClass().getName());

        // These special array classes extend class java.lang.Object, just like any Java class.
        if (numbers instanceof Object) {
            System.out.println("It's true, arrays are objects.");
        }
    }
}
